# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
nombre = "Ceneida Aliceth Durango Sanchez"
edad = 36
print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Ceneida Aliceth Durango Sanchez y tengo 36 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [5]:
numeros = [10, 25, 3, 47, 8, 15]
numeros = [10, 25, 3, 47, 8, 15]

print("Primero:", numeros[0])
print("Último:", numeros[-1])
print("Tres primeros elementos:", numeros[:3])

numeros.append(99)
print(numeros)

Primero: 10
Último: 15
Tres primeros elementos: [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [9]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [10]:
def calcular_area(base, altura):
    return (base * altura) / 2


resultado = calcular_area(5, 8)
print(resultado)

20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [11]:
cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [16]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [17]:
# 1. Arreglo con valores decimales
arreglo1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:", arreglo1)
print("Shape:", arreglo1.shape)
print("Dtype:", arreglo1.dtype)

# 2. Matriz de ceros de 3 filas x 4 columnas
matriz_ceros = np.zeros((3, 4))
print("\nMatriz de ceros:")
print(matriz_ceros)
print("Shape:", matriz_ceros.shape)
print("Dtype:", matriz_ceros.dtype)

# 3. Arreglo con 6 valores entre 0 y 1
arreglo2 = np.linspace(0, 1, 6)
print("\nArreglo 2:", arreglo2)
print("Shape:", arreglo2.shape)
print("Dtype:", arreglo2.dtype)

Arreglo 1: [1.5 2.5 3.5 4.5]
Shape: (4,)
Dtype: float64

Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64

Arreglo 2: [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [18]:
a = np.arange(1, 13)
matriz = a.reshape(3, 4)

print("Matriz:")
print(matriz)
print("Máximo:", matriz.max())
print("Mínimo:", matriz.min())
print("Índice del máximo:", matriz.argmax())

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Máximo: 12
Mínimo: 1
Índice del máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [19]:
arreglo1 = np.random.randint(1, 21, 5)
arreglo2 = np.random.randint(1, 21, 5)

print("Arreglo 1:", arreglo1)
print("Arreglo 2:", arreglo2)
print("Suma:", arreglo1 + arreglo2)
print("Resta:", arreglo1 - arreglo2)
print("Multiplicación:", arreglo1 * arreglo2)

Arreglo 1: [16  4 14 18 19]
Arreglo 2: [16 13  5  7  8]
Suma: [32 17 19 25 27]
Resta: [ 0 -9  9 11 11]
Multiplicación: [256  52  70 126 152]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [20]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

notas_aprobadas = notas[notas >= 6]
print(notas_aprobadas)

[ 8.5  6.   9.2  7.8 10. ]
